import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";

const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["latin", "thai"],
  weight: ["300", "400", "700"],
});

export const metadata = {
  title: "Human Resource Management",
  description: "Generated by Peem",
};

export default function RootLayout({ children }) {
  return (
    <html lang="th">
      <body className={`${notoSansThai.variable} no-margin`}>
        {children}
      </body>
    </html>
  );
}
